# Generated by Django 3.1.1 on 2020-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200918_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('demo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=330)),
                ('phone', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
