# Generated by Django 3.1.1 on 2020-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200922_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='phone',
            field=models.IntegerField(max_length=2),
        ),
    ]
