# Generated by Django 3.1.1 on 2020-09-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200922_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
